import { useMemo, useState } from "react";
import { Activity, BarChart3, CheckCircle2, MapPinned, Search, ShieldCheck, TrendingUp, UserCheck, UserX, Users } from "lucide-react";

interface Trip { name: string; }
interface AdminUser { id: number; name: string; email: string; trips: number; status: "Active" | "Suspended"; joined: string; }

const initialUsers: AdminUser[] = [
  { id: 1, name: "Aarav Sharma", email: "aarav@example.com", trips: 8, status: "Active", joined: "Aug 2026" },
  { id: 2, name: "Maya Chen", email: "maya@example.com", trips: 5, status: "Active", joined: "Jul 2026" },
  { id: 3, name: "Noah Williams", email: "noah@example.com", trips: 2, status: "Suspended", joined: "Jul 2026" },
  { id: 4, name: "Sofia Martin", email: "sofia@example.com", trips: 11, status: "Active", joined: "Jun 2026" },
];

const cityStats = [{ label: "Tokyo", value: 82 }, { label: "Lisbon", value: 68 }, { label: "Kyoto", value: 61 }, { label: "Paris", value: 54 }, { label: "Marrakech", value: 43 }];
const activityStats = [{ label: "Sightseeing", value: 74, color: "bg-sky-500" }, { label: "Food tours", value: 58, color: "bg-amber-500" }, { label: "Adventure", value: 46, color: "bg-emerald-500" }];

export default function AdminDashboardPage() {
  const trips = JSON.parse(localStorage.getItem("globetrotter_trips") || "[]") as Trip[];
  const [users, setUsers] = useState(initialUsers);
  const [query, setQuery] = useState("");
  const filteredUsers = useMemo(() => users.filter((user) => `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase())), [users, query]);

  function toggleUser(id: number) {
    setUsers((current) => current.map((user) => user.id === id ? { ...user, status: user.status === "Active" ? "Suspended" : "Active" } : user));
  }

  return (
    <div className="min-h-screen bg-slate-50"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
      <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-slate-500"><ShieldCheck size={16} /> Admin console</p><h1 className="text-3xl font-bold tracking-tight text-slate-950">Platform overview</h1><p className="mt-2 text-slate-600">Monitor adoption, trip planning, and community activity.</p></div><span className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-700"><CheckCircle2 size={16} /> Systems operational</span></div>
      <section className="mb-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl bg-slate-950 p-5 text-white"><Users size={20} className="text-slate-300" /><p className="mt-5 text-sm text-slate-400">Total users</p><p className="mt-1 text-3xl font-bold">1,284</p><p className="mt-2 flex items-center gap-1 text-xs text-emerald-300"><TrendingUp size={13} /> +12.8% this month</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><BarChart3 size={20} className="text-sky-600" /><p className="mt-5 text-sm text-slate-500">Trips created</p><p className="mt-1 text-3xl font-bold text-slate-950">{128 + trips.length}</p><p className="mt-2 text-xs text-slate-500">+18% vs last month</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><MapPinned size={20} className="text-amber-600" /><p className="mt-5 text-sm text-slate-500">Cities explored</p><p className="mt-1 text-3xl font-bold text-slate-950">96</p><p className="mt-2 text-xs text-slate-500">Across 42 countries</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><Activity size={20} className="text-emerald-600" /><p className="mt-5 text-sm text-slate-500">Weekly engagement</p><p className="mt-1 text-3xl font-bold text-slate-950">68.4%</p><p className="mt-2 text-xs text-emerald-700">+4.2% active users</p></div></section>
      <section className="mb-8 grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-7 flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-950">Trip creation trend</h2><p className="mt-1 text-sm text-slate-500">New trips over the last six months.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">+18.6%</span></div><div className="flex h-48 items-end gap-3 border-b border-l border-slate-200 px-4 pb-0 pt-4 sm:gap-6">{[38, 52, 44, 68, 78, 96].map((value, index) => <div key={value} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className="w-full max-w-10 rounded-t-md bg-sky-500 transition hover:bg-sky-600" style={{ height: `${value}%` }} /><span className="text-xs text-slate-400">{["Mar", "Apr", "May", "Jun", "Jul", "Aug"][index]}</span></div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-6"><h2 className="text-lg font-bold text-slate-950">Popular activities</h2><p className="mt-1 text-sm text-slate-500">Most added this month.</p></div><div className="space-y-5">{activityStats.map((item) => <div key={item.label}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold text-slate-800">{item.label}</span><span className="text-slate-500">{item.value}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.color}`} style={{ width: `${item.value}%` }} /></div></div>)}</div></div></section>
      <section className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-6"><h2 className="text-lg font-bold text-slate-950">Top cities</h2><p className="mt-1 text-sm text-slate-500">Where users are planning to go.</p></div><div className="space-y-4">{cityStats.map((city, index) => <div key={city.label} className="flex items-center gap-3"><span className="w-5 text-xs font-bold text-slate-400">0{index + 1}</span><span className="w-20 text-sm font-semibold text-slate-800">{city.label}</span><div className="h-2 flex-1 rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-800" style={{ width: `${city.value}%` }} /></div><span className="w-8 text-right text-xs text-slate-500">{city.value}</span></div>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col justify-between gap-4 border-b border-slate-100 p-6 sm:flex-row sm:items-center"><div><h2 className="text-lg font-bold text-slate-950">User management</h2><p className="mt-1 text-sm text-slate-500">Review and manage platform accounts.</p></div><div className="relative sm:w-64"><Search size={16} className="pointer-events-none absolute left-3 top-3 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search users" className="w-full rounded-lg border border-slate-300 py-2 pl-9 pr-3 text-sm outline-none focus:border-slate-950" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-6 py-3 font-semibold">User</th><th className="px-6 py-3 font-semibold">Trips</th><th className="px-6 py-3 font-semibold">Joined</th><th className="px-6 py-3 font-semibold">Status</th><th className="px-6 py-3 font-semibold">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{filteredUsers.map((user) => <tr key={user.id}><td className="px-6 py-4"><p className="font-semibold text-slate-900">{user.name}</p><p className="text-xs text-slate-500">{user.email}</p></td><td className="px-6 py-4 text-slate-600">{user.trips}</td><td className="px-6 py-4 text-slate-600">{user.joined}</td><td className="px-6 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${user.status === "Active" ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{user.status}</span></td><td className="px-6 py-4"><button type="button" onClick={() => toggleUser(user.id)} className="inline-flex items-center gap-1 text-xs font-semibold text-slate-600 hover:text-slate-950">{user.status === "Active" ? <><UserX size={14} /> Suspend</> : <><UserCheck size={14} /> Activate</>}</button></td></tr>)}</tbody></table></div></div></section>
    </div></div>
  );
}
